# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSEAllOFF():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_sEAllOFF(self):
    self.driver.get("http://localhost:8080/entity-wizard")
    self.driver.set_window_size(1552, 840)
    with open('./jquery-3.5.1.min.js', errors='ignore') as f:
      self.driver.execute_script(f.read())
    with open("./drag_and_drop_helper.js") as f:
      self.js = f.read()
    self.driver.find_element(By.ID, "entity-wizard-title").click()
    self.driver.find_element(By.ID, "entity-wizard-title").send_keys("Medya")
    self.driver.find_element(By.ID, "entity-wizard-name").send_keys("Medya")
    self.driver.find_element(By.CSS_SELECTOR, ".button_button--contained--secondary__3sWmt > .button_button__label__17Z4y").click()
    # dragged = self.driver.find_element(By.CSS_SELECTOR, "")
    # dropped = self.driver.find_element(By.CSS_SELECTOR, "")
    actions = ActionChains(self.driver)
    self.driver.execute_script(self.js + "$('.accordion_accordion__lJAWV:nth-child(3) .container_container__u60WU:nth-child(1)').simulateDragDrop({ dropTarget: '.entity-wizard__form'})")
    # actions.drag_and_drop(dragged, dropped).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".entity-wizard__field-tile > .typography_typography--variant_body__1Gzqi").click()
    self.driver.find_element(By.CSS_SELECTOR, ".entity-wizard__field-tile > .typography_typography--variant_body__1Gzqi").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".entity-wizard__field-tile > .typography_typography--variant_body__1Gzqi")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".accordion_accordion__lJAWV:nth-child(1) .grid_grid--conainer__RaJcR > .grid_grid--conainer__RaJcR:nth-child(1)").click()
    self.driver.find_element(By.ID, "entity-wizard-field-title").send_keys("Medya HELPED")
    self.driver.find_element(By.ID, "entity-wizard-field-name").send_keys("Medya HELPED")
    self.driver.find_element(By.XPATH, "//div[2]/div[2]/div/div/div/div[2]/div/div/input").click()
    self.driver.find_element(By.XPATH, "//div[2]/div[2]/div/div/div/div[2]/div/div/input").send_keys("DefaultValue")
    self.driver.find_element(By.XPATH, "//div[3]/div[2]/div/div/input").click()
    self.driver.find_element(By.XPATH, "//div[3]/div[2]/div/div/input").send_keys("ExplanationText")
    self.driver.find_element(By.XPATH, "//div[5]/div[2]/div/div/input").click()
    self.driver.find_element(By.XPATH, "//div[5]/div[2]/div/div/input").send_keys("HelperText")
    self.driver.find_element(By.XPATH, "//div[6]/div[2]/div/div/input").send_keys("4")
    self.driver.find_element(By.XPATH, "//div[7]/div[2]/div/div/input").click()
    self.driver.find_element(By.XPATH, "//div[7]/div[2]/div/div/input").send_keys("4")
    self.driver.find_element(By.CSS_SELECTOR, ".grid_grid--item__2VyyC:nth-child(1) > .button_button--contained--primary__3dAwk").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button_button--contained--primary__3dAwk > .button_button__label__17Z4y").click()
    self.driver.close()
  
